# Copyright (c) HashiCorp, Inc.

version: '3.8'
services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    command: vault server -config=/etc/vault.d/config.hcl
    cap_add:
      - IPC_LOCK
    ports:
      - 8205:8205
      - 8206:8206
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8205
      VAULT_ADDR: http://localhost:8205
      VAULT_LOG_LEVEL: trace
    volumes:
      - "./config.hcl:/etc/vault.d/config.hcl:ro"
      - "vault_ce_1_raft:/vault/file"
volumes:
  vault_ce_1_raft:
